ALTER TRIGGER DT_PENJUALAN_AI4
ACTIVE AFTER 
  INSERT
POSITION 4
AS
DECLARE VARIABLE PENANDA VARCHAR(200);
DECLARE VARIABLE HARGA_UMUM DECIMAL(18, 2);
DECLARE VARIABLE HARGA_RESELLER DECIMAL(18, 2);
DECLARE VARIABLE GUDANG VARCHAR(20);
DECLARE VARIABLE STANDAR_GUDANG SMALLINT;
BEGIN
  --CUSTOM TRIGGER
  SELECT PENANDA_ACTION FROM MST_CONFIG
  INTO :PENANDA;
  
  IF(COALESCE(PENANDA,'') = 'SUNDA MOTOR') THEN
  BEGIN
  	SELECT A.KODE_GUDANG, COALESCE(B.STANDAR,0)
    FROM MT_PENJUALAN A
    LEFT JOIN MST_GUDANG B ON B.KODE_GUDANG = A.KODE_GUDANG
    WHERE NO_FAKTUR = NEW.NO_FAKTUR
    INTO :GUDANG,:STANDAR_GUDANG;
  	
    --CARI HARGA TERTINGGI DAN TERENDAH DALAM 1 BULAN TERAKHIR DI BARANG TERPILIH
    SELECT
    MAX(HARGA) HARGA_TERTINGGI,
    MIN(HARGA) HARGA_TERENDAH
    FROM MT_PENJUALAN A
    INNER JOIN DT_PENJUALAN B ON B.NO_FAKTUR = A.NO_FAKTUR
    INNER JOIN MST_BARANG_JUAL C ON C.KODE_JUAL = B.KODE_BARANG AND C.KODE_SATUAN = B.KODE_SATUAN
    INNER JOIN MST_BARANG D ON D.KODE_BARANG = C.KODE_BARANG
    WHERE A.TANGGAL BETWEEN CURRENT_DATE - 30 AND CURRENT_DATE
    AND B.KODE_BARANG = NEW.KODE_BARANG AND B.KODE_SATUAN = NEW.KODE_SATUAN
    AND A.KODE_GUDANG = :GUDANG
    INTO :HARGA_UMUM,:HARGA_RESELLER;
   
  	-- update harga pada gudang terpilih
    IF(COALESCE(HARGA_UMUM,0) > 0 AND COALESCE(HARGA_RESELLER,0) > 0) THEN
      BEGIN
        IF(STANDAR_GUDANG = 0) THEN
        BEGIN
           UPDATE MST_BARANG_JUAL_GUDANG
           SET
           HARGA_JUAL = :HARGA_UMUM,
           HARGA_JUAL2 = :HARGA_RESELLER
           WHERE KODE_GUDANG = :GUDANG AND
           KODE_JUAL = NEW.KODE_BARANG AND
           KODE_SATUAN = NEW.KODE_SATUAN;
        END
        ELSE
        BEGIN
            UPDATE MST_BARANG_JUAL
            SET
            HARGA_JUAL = :HARGA_UMUM,
            HARGA_JUAL2 = :HARGA_RESELLER
            WHERE KODE_JUAL = NEW.KODE_BARANG AND
            KODE_SATUAN = NEW.KODE_SATUAN;
        END
     END
  END
END;
