CREATE PROCEDURE GET_JUMLAHSALDO(
  BULAN SMALLINT,
  TAHUN SMALLINT,
  KODE VARCHAR(20),
  PARENT SMALLINT)
RETURNS(
  JUMLAH DECIMAL(18, 2))
AS
BEGIN
  EXECUTE STATEMENT
  'SELECT sum(COALESCE(A.D,0) - abs(COALESCE(A.K,0)))total
  FROM DT_RINCIANSALDO A
  LEFT JOIN MST_COA B ON B.KODE_COA = A.KODE_COA
  WHERE EXTRACT(MONTH FROM A.TANGGAL_TRANSAKSI) = '|| BULAN ||'
  AND EXTRACT(YEAR FROM A.TANGGAL_TRANSAKSI) = '|| TAHUN ||'
  AND ' || IIF(COALESCE(PARENT,0) = 0, 'B.KODE_COA =' , 'B.PARENT_COA =') || '''' || KODE || ''''
  INTO :JUMLAH;
  SUSPEND;
END;
