CREATE PROCEDURE LABARUGI_CIPTO_ONLINE(
  BULAN SMALLINT,
  TAHUN BIGINT)
RETURNS(
  TOTAL_PENJUALAN DECIMAL(18, 2),
  TOTAL_HPP_KOTOR DECIMAL(18, 2),
  TOTAL_DISCOUNT DECIMAL(18, 2),
  TOTAL_RETUR_PENJUALAN DECIMAL(18, 2),
  TOTAL_HPP_RETUR DECIMAL(18, 2),
  TOTAL_RETUR_PEMBELIAN DECIMAL(18, 2),
  TOTAL_STOK_TERSEDIA DECIMAL(18, 2),
  TOTAL_PEMBELIAN DECIMAL(18, 2),
  TOTAL_STOK_AKHIR DECIMAL(18, 2),
  TOTAL_PPN DECIMAL(18, 2),
  TOTAL_PENJUALAN_NET DECIMAL(18, 2),
  TOTAL_HPP_PENJUALAN DECIMAL(18, 2),
  TOTAL_LABA_BRUTO DECIMAL(18, 2),
  /* KEBAWAH ADALAH UNTUK OPRASIONAL */
  OP_GAJI DECIMAL(18, 2),
  OP_TUNJANGAN_LEBARAN DECIMAL(18, 2),
  OP_TUNJANGAN_SERANGAM DECIMAL(18, 2),
  OP_INSENTIF_BONUS DECIMAL(18, 2),
  OP_PROMOSI DECIMAL(18, 2),
  OP_LISTRIK DECIMAL(18, 2),
  OP_TELEPON DECIMAL(18, 2),
  OP_PDAM DECIMAL(18, 2),
  OP_INTERNET DECIMAL(18, 2),
  OP_BENSIN DECIMAL(18, 2),
  OP_CETAKAN DECIMAL(18, 2),
  OP_ATK DECIMAL(18, 2),
  OP_ALAT_TOKO DECIMAL(18, 2),
  OP_ALAT_GUDANG DECIMAL(18, 2),
  OP_LENGKAP_TOKO DECIMAL(18, 2),
  OP_LENGKAP_GUDANG DECIMAL(18, 2),
  OP_LENGKAP_KANTOR DECIMAL(18, 2),
  OP_MATERAI DECIMAL(18, 2),
  OP_FOTOCOPY DECIMAL(18, 2),
  OP_PARKIR DECIMAL(18, 2),
  OP_ANTAR_DOKUMEN DECIMAL(18, 2),
  OP_POS DECIMAL(18, 2),
  OP_BIAYA_PERIJINAN DECIMAL(18, 2),
  OP_BIAYA_STNK DECIMAL(18, 2),
  OP_BIAYA_NOTARIS DECIMAL(18, 2),
  OP_AKOMODASI DECIMAL(18, 2),
  OP_MAKANAN DECIMAL(18, 2),
  OP_PRODUKSI DECIMAL(18, 2),
  OP_BONGKAR_MUAT DECIMAL(18, 2),
  OP_KIRIM_BARANG DECIMAL(18, 2),
  OP_PERJALANAN_DINAS DECIMAL(18, 2),
  OP_ENTERTAIMENT DECIMAL(18, 2),
  OP_KENDARAAN DECIMAL(18, 2),
  OP_GEDUNG DECIMAL(18, 2),
  OP_ADM_BANK DECIMAL(18, 2),
  OP_SEWA_GEDUNG DECIMAL(18, 2),
  OP_PPH21 DECIMAL(18, 2),
  OP_PPH22 DECIMAL(18, 2),
  OP_PPH23 DECIMAL(18, 2),
  OP_PPH25 DECIMAL(18, 2),
  OP_KASBON DECIMAL(18, 2),
  OP_PRIVE DECIMAL(18, 2),
  PENDAPATAN_CLAIM DECIMAL(18, 2),
  PENDAPATAN_GIRO DECIMAL(18, 2),
  /* AKHIR OPRASIONAL */
  TOTAL_BIAYA_OPERASIONAL DECIMAL(18, 2),
  LABA_BERSIH_OPERASIONAL DECIMAL(18, 2),
  TOTAL_PENDAPATAN_LAINNYA DECIMAL(18, 2),
  LABA_RUGI_BESIH DECIMAL(18, 2))
AS
BEGIN
  --CARI TOTAL PENJUALAN
  SELECT
  SUM(B.HARGA * B.QTY)TOTAL_PENJUALAN, SUM((B.HARGA * B.QTY) - B.SUBTOTAL), SUM(B.QTY * B.HARGA_BELI)
  FROM MT_PENJUALAN A
  INNER JOIN DT_PENJUALAN B ON B.NO_FAKTUR = A.NO_FAKTUR
  WHERE COALESCE(A.BATAL,0) = 0
  AND EXTRACT(MONTH FROM A.TANGGAL) = :BULAN
  AND EXTRACT(YEAR FROM A.TANGGAL) = :TAHUN
  INTO :TOTAL_PENJUALAN, :TOTAL_DISCOUNT,:TOTAL_HPP_KOTOR;
  
  -- CARI RETUR PENJUALAN
  SELECT
  SUM(B.HARGA * B.QTY) TOTAL_RETUR, SUM(B.HARGA_BELI * B.QTY) HPP_RETUR
  FROM MT_RETUR_PENJUALAN A
  INNER JOIN DT_RETUR_PENJUALAN B ON B.NO_RETUR = A.NO_RETUR
  WHERE COALESCE(A.BATAL,0) = 0
  AND EXTRACT(MONTH FROM A.TANGGAL) = :BULAN
  AND EXTRACT(YEAR FROM A.TANGGAL) = :TAHUN
  INTO :TOTAL_RETUR_PENJUALAN, :TOTAL_HPP_RETUR;
  
  --CARI TOTAL PEMBELIAN
  SELECT
  SUM(B.HARGA * B.QTY)TOTAL_PENJUALAN
  FROM MT_PEMBELIAN A
  INNER JOIN DT_PEMBELIAN B ON B.NO_FAKTUR = A.NO_FAKTUR
  WHERE COALESCE(A.BATAL,0) = 0
  AND EXTRACT(MONTH FROM A.TANGGAL) = :BULAN
  AND EXTRACT(YEAR FROM A.TANGGAL) = :TAHUN
  INTO :TOTAL_PEMBELIAN;
  
  -- CARI RETUR PEMBELIAN
  SELECT
  SUM(B.HARGA * B.QTY) TOTAL_RETUR
  FROM MT_RETUR_PEMBELIAN A
  INNER JOIN DT_RETUR_PEMBELIAN B ON B.NO_RETUR = A.NO_RETUR
  WHERE COALESCE(A.BATAL,0) = 0
  AND EXTRACT(MONTH FROM A.TANGGAL) = :BULAN
  AND EXTRACT(YEAR FROM A.TANGGAL) = :TAHUN
  INTO :TOTAL_RETUR_PEMBELIAN;
  
  -- HITUNG PPN, PENJUALAN NET, HPP, DAN LABA BRUTO
  TOTAL_PPN = ((COALESCE(TOTAL_PENJUALAN,0) - COALESCE(TOTAL_RETUR_PENJUALAN,0) - COALESCE(TOTAL_DISCOUNT,0)) / 1.1) / 100 * 10;
  TOTAL_PENJUALAN_NET = COALESCE(TOTAL_PENJUALAN,0) - COALESCE(TOTAL_RETUR_PENJUALAN,0) - COALESCE(TOTAL_DISCOUNT,0) - COALESCE(TOTAL_PPN,0);
  TOTAL_HPP_PENJUALAN = (COALESCE(TOTAL_HPP_KOTOR,0) - COALESCE(TOTAL_HPP_RETUR,0)) / 1.1;
  TOTAL_LABA_BRUTO = COALESCE(TOTAL_PENJUALAN_NET,0) - COALESCE(TOTAL_HPP_PENJUALAN,0);
  
  -- OPRASIONAL
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'601',0) INTO :OP_GAJI; 
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'615',0) INTO :OP_TUNJANGAN_LEBARAN;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'617',0) INTO :OP_INSENTIF_BONUS; 
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'616',0) INTO :OP_TUNJANGAN_SERANGAM; 
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'620',0) INTO :OP_PROMOSI; 
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'621',0) INTO :OP_LISTRIK;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'622',0) INTO :OP_TELEPON; 
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'623',0) INTO :OP_PDAM;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'624',0) INTO :OP_INTERNET;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'625',1) INTO :OP_BENSIN;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'626',0) INTO :OP_CETAKAN;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'627',0) INTO :OP_ATK;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'628',0) INTO :OP_ALAT_TOKO;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'629',0) INTO :OP_ALAT_GUDANG;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'631',0) INTO :OP_LENGKAP_TOKO;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'630',0) INTO :OP_LENGKAP_KANTOR;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'632',0) INTO :OP_LENGKAP_GUDANG;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'633',0) INTO :OP_MATERAI;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'634',0) INTO :OP_FOTOCOPY;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'635',0) INTO :OP_PARKIR;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'636',0) INTO :OP_ANTAR_DOKUMEN;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'637',0) INTO :OP_POS;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'638',0) INTO :OP_BIAYA_PERIJINAN;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'639',0) INTO :OP_BIAYA_STNK;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'640',0) INTO :OP_BIAYA_NOTARIS;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'650',0) INTO :OP_AKOMODASI;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'651',0) INTO :OP_MAKANAN;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'652',0) INTO :OP_PRODUKSI;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'653',0) INTO :OP_BONGKAR_MUAT;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'654',0) INTO :OP_KIRIM_BARANG;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'655',0) INTO :OP_PERJALANAN_DINAS;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'656',0) INTO :OP_ENTERTAIMENT;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'673',0) INTO :OP_KENDARAAN;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'674',0) INTO :OP_GEDUNG;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'675',0) INTO :OP_ADM_BANK;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'182',0) INTO :OP_SEWA_GEDUNG;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'680',0) INTO :OP_PPH21;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'681',0) INTO :OP_PPH22;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'682',0) INTO :OP_PPH23;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'683',0) INTO :OP_PPH25;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'604',0) INTO :OP_KASBON;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'330',0) INTO :OP_PRIVE;
  
  --PENDAPATAN LAIN
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'705',0) INTO :PENDAPATAN_CLAIM;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'701',0) INTO :PENDAPATAN_GIRO;
  
  TOTAL_BIAYA_OPERASIONAL = COALESCE(OP_GAJI,0) +
                            COALESCE(OP_TUNJANGAN_LEBARAN,0) +
                            COALESCE(OP_TUNJANGAN_SERANGAM,0) +
                            COALESCE(OP_INSENTIF_BONUS,0) +
                            COALESCE(OP_PROMOSI,0) +
                            COALESCE(OP_LISTRIK,0) +
                            COALESCE(OP_TELEPON,0) +
                            COALESCE(OP_PDAM,0) +
                            COALESCE(OP_INTERNET,0) +
                            COALESCE(OP_BENSIN,0) +
                            COALESCE(OP_CETAKAN,0) +
                            COALESCE(OP_ATK,0) +
                            COALESCE(OP_ALAT_TOKO,0) +
                            COALESCE(OP_ALAT_GUDANG,0) +
                            COALESCE(OP_LENGKAP_TOKO,0) +
                            COALESCE(OP_LENGKAP_GUDANG,0) +
                            COALESCE(OP_LENGKAP_KANTOR,0) +
                            COALESCE(OP_MATERAI,0) +
                            COALESCE(OP_FOTOCOPY,0) +
                            COALESCE(OP_PARKIR,0) +
                            COALESCE(OP_ANTAR_DOKUMEN,0) +
                            COALESCE(OP_POS,0) +
                            COALESCE(OP_BIAYA_PERIJINAN,0) +
                            COALESCE(OP_BIAYA_STNK,0) +
                            COALESCE(OP_BIAYA_NOTARIS,0) +
                            COALESCE(OP_AKOMODASI,0) +
                            COALESCE(OP_MAKANAN,0) +
                            COALESCE(OP_PRODUKSI,0) +
                            COALESCE(OP_BONGKAR_MUAT,0) +
                            COALESCE(OP_KIRIM_BARANG,0) +
                            COALESCE(OP_PERJALANAN_DINAS,0) +
                            COALESCE(OP_ENTERTAIMENT,0) +
                            COALESCE(OP_KENDARAAN,0) +
                            COALESCE(OP_GEDUNG,0) +
                            COALESCE(OP_ADM_BANK,0) +
                            COALESCE(OP_SEWA_GEDUNG,0) +
                            COALESCE(OP_PPH21,0) +
                            COALESCE(OP_PPH22,0) +
                            COALESCE(OP_PPH23,0) +
                            COALESCE(OP_PPH25,0) +
                            COALESCE(OP_KASBON,0) +
                            COALESCE(OP_PRIVE,0);
  
  LABA_BERSIH_OPERASIONAL = COALESCE(TOTAL_LABA_BRUTO,0) - COALESCE(TOTAL_BIAYA_OPERASIONAL,0);
  TOTAL_PENDAPATAN_LAINNYA = COALESCE(PENDAPATAN_CLAIM,0) + COALESCE(PENDAPATAN_GIRO,0);
  
  LABA_RUGI_BESIH = COALESCE(LABA_BERSIH_OPERASIONAL,0) + COALESCE(TOTAL_PENDAPATAN_LAINNYA,0);
  SUSPEND;
END;
