CREATE PROCEDURE LABARUGI_MIWON_REV(
  BULAN SMALLINT,
  TAHUN BIGINT)
RETURNS(
  PENJUALAN_MIWON DECIMAL(18, 2),
  PENJUALAN_GULA DECIMAL(18, 2),
  RETUR_GS DECIMAL(18, 2),
  RETUR_GULA DECIMAL(18, 2),
  DISCOUNT DECIMAL(18, 2),
  PPN10 DECIMAL(18, 2),
  STOCK_AWAL_GULA DECIMAL(18, 2),
  PEMBELIAN_GULA DECIMAL(18, 2),
  PEMBELIAN_MIWON DECIMAL(18, 2),
  STOCK_BARANG DECIMAL(18, 2),
  HARGA_POKOK_PEMBELIAN DECIMAL(18, 2),
  BTK_GAJI DECIMAL(18, 2),
  TUNJANGAN_THR DECIMAL(18, 2),
  TUNJANGAN_SERAGAM DECIMAL(18, 2),
  INSENTIF DECIMAL(18, 2),
  BBJPK_PROMOSI DECIMAL(18, 2),
  BBKPK_LISTRIK DECIMAL(18, 2),
  BBKPK_TELPON DECIMAL(18, 2),
  BBKPK_AIR DECIMAL(18, 2),
  BBKPK_KOM DECIMAL(18, 2),
  BBKPK_BBM DECIMAL(18, 2),
  BBKPK_CETAKAN DECIMAL(18, 2),
  BBKPK_ATK DECIMAL(18, 2),
  BBKPK_ALATTOKO DECIMAL(18, 2),
  BBKPK_ALATGUDANG DECIMAL(18, 2),
  BBKPK_LENGKAPTOKO DECIMAL(18, 2),
  BBKPK_LENGKAPKANTOR DECIMAL(18, 2),
  BBKPK_LENGKAPGUDANG DECIMAL(18, 2),
  BBKPK_MATERAI DECIMAL(18, 2),
  BBKPK_FOTOCOPY DECIMAL(18, 2),
  BBKPK_PARKIR DECIMAL(18, 2),
  BBKPK_ANTARDOC DECIMAL(18, 2),
  BBKPK_POS DECIMAL(18, 2),
  BBKPK_IZIN DECIMAL(18, 2),
  BBKPK_STNK DECIMAL(18, 2),
  BBKPK_NOTARIS DECIMAL(18, 2),
  BOL_AKOMODASI DECIMAL(18, 2),
  BOL_KONSUMSI DECIMAL(18, 2),
  BOL_PRODUKSI DECIMAL(18, 2),
  BOL_BONGKARAN DECIMAL(18, 2),
  BOL_KIRIMLUAR DECIMAL(18, 2),
  BOL_TRIPBISNIS DECIMAL(18, 2),
  BOL_ENTERTAIMENT DECIMAL(18, 2),
  BPP_KENDARAAN DECIMAL(18, 2),
  BPP_GEDUNG DECIMAL(18, 2),
  BYA_ADMINBANK DECIMAL(18, 2),
  BYA_SEWAGEDUNG DECIMAL(18, 2),
  PPH21 DECIMAL(18, 2),
  PPH22 DECIMAL(18, 2),
  PPH23 DECIMAL(18, 2),
  PPH2529 DECIMAL(18, 2),
  PENDAPATAN_CLAIM DECIMAL(18, 2),
  PENDAPATAN_GIRO DECIMAL(18, 2),
  TOTAL_OPERASIONAL DECIMAL(18, 2),
  HPP_MIWON DECIMAL(18, 2),
  HPP_GULA DECIMAL(18, 2))
AS
DECLARE VARIABLE HPP_KOTOR_MIWON DECIMAL(18, 2);
DECLARE VARIABLE HPP_KOTOR_MIWON_RETUR DECIMAL(18, 2);
DECLARE VARIABLE HPP_KOTOR_GULA DECIMAL(18, 2);
DECLARE VARIABLE HPP_KOTOR_GULA_RETUR DECIMAL(18, 2);
BEGIN
  --CARI TOTAL PENJUALAN
  SELECT
  SUM(B.HARGA * B.QTY)TOTAL_PENJUALAN, SUM((B.HARGA * B.QTY) - B.SUBTOTAL), SUM(B.QTY * B.HARGA_BELI)
  FROM MT_PENJUALAN A
  INNER JOIN DT_PENJUALAN B ON B.NO_FAKTUR = A.NO_FAKTUR
  INNER JOIN MST_BARANG_JUAL C ON C.KODE_JUAL = B.KODE_BARANG
                               AND C.KODE_SATUAN = B.KODE_SATUAN
  INNER JOIN MST_BARANG D ON D.KODE_BARANG = C.KODE_BARANG
  WHERE COALESCE(A.BATAL,0) = 0
  AND EXTRACT(MONTH FROM A.TANGGAL) = :BULAN
  AND EXTRACT(YEAR FROM A.TANGGAL) = :TAHUN
  INTO :PENJUALAN_MIWON, :DISCOUNT, HPP_KOTOR_MIWON;
  
  --PENJUALAN GULA
  SELECT
  SUM(B.HARGA * B.QTY)TOTAL_PENJUALAN , SUM(B.QTY * B.HARGA_BELI)
  FROM MT_PENJUALAN A
  INNER JOIN DT_PENJUALAN B ON B.NO_FAKTUR = A.NO_FAKTUR
  INNER JOIN MST_BARANG_JUAL C ON C.KODE_JUAL = B.KODE_BARANG
                               AND C.KODE_SATUAN = B.KODE_SATUAN
  INNER JOIN MST_BARANG D ON D.KODE_BARANG = C.KODE_BARANG
  WHERE COALESCE(A.BATAL,0) = 0
  AND COALESCE(D.KODE_GROUPBARANG,'') = 'GULA'
  AND EXTRACT(MONTH FROM A.TANGGAL) = :BULAN
  AND EXTRACT(YEAR FROM A.TANGGAL) = :TAHUN
  INTO :PENJUALAN_GULA, :HPP_KOTOR_GULA;
  
  --RETUR GULA DAN MIWON
  SELECT
  SUM(B.SUBTOTAL), SUM(B.HARGA_BELI * B.QTY)
  FROM MT_RETUR_PENJUALAN A
  INNER JOIN DT_RETUR_PENJUALAN B ON B.NO_RETUR = A.NO_RETUR
  INNER JOIN MST_BARANG_JUAL C ON C.KODE_JUAL = B.KODE_BARANG
                             AND C.KODE_SATUAN = B.KODE_SATUAN
  INNER JOIN MST_BARANG D ON D.KODE_BARANG = C.KODE_BARANG
  WHERE COALESCE(A.BATAL,0) = 0
  AND EXTRACT(MONTH FROM A.TANGGAL) = :BULAN
  AND EXTRACT(YEAR FROM A.TANGGAL) = :TAHUN
  INTO :RETUR_GS, :HPP_KOTOR_MIWON_RETUR;
  
  SELECT
  SUM(B.SUBTOTAL), SUM(B.QTY * B.HARGA_BELI)
  FROM MT_RETUR_PENJUALAN A
  INNER JOIN DT_RETUR_PENJUALAN B ON B.NO_RETUR = A.NO_RETUR
  INNER JOIN MST_BARANG_JUAL C ON C.KODE_JUAL = B.KODE_BARANG
                             AND C.KODE_SATUAN = B.KODE_SATUAN
  INNER JOIN MST_BARANG D ON D.KODE_BARANG = C.KODE_BARANG
  WHERE COALESCE(A.BATAL,0) = 0
  AND COALESCE(D.KODE_GROUPBARANG,'') = 'GULA'
  AND EXTRACT(MONTH FROM A.TANGGAL) = :BULAN
  AND EXTRACT(YEAR FROM A.TANGGAL) = :TAHUN
  INTO :RETUR_GULA, :HPP_KOTOR_GULA_RETUR;
  
  PEMBELIAN_MIWON = (COALESCE(HPP_KOTOR_MIWON,0) - COALESCE(HPP_KOTOR_MIWON_RETUR,0)) / 1.1;
  PEMBELIAN_GULA = COALESCE(HPP_KOTOR_GULA,0) - COALESCE(HPP_KOTOR_GULA_RETUR,0);
  PPN10 = ((COALESCE(PENJUALAN_MIWON,0) - COALESCE(RETUR_GS,0) - COALESCE(DISCOUNT,0)) / 1.1) / 100 * 10;
 
  -- OPERASIONAL
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'601',0) INTO :BTK_GAJI; 
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'615',0) INTO :TUNJANGAN_THR;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'617',0) INTO :INSENTIF; 
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'616',0) INTO :TUNJANGAN_SERAGAM; 
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'620',0) INTO :BBJPK_PROMOSI; 
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'621',0) INTO :BBKPK_LISTRIK;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'622',0) INTO :BBKPK_TELPON; 
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'623',0) INTO :BBKPK_AIR;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'624',0) INTO :BBKPK_KOM;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'625',1) INTO :BBKPK_BBM;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'626',0) INTO :BBKPK_CETAKAN;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'627',0) INTO :BBKPK_ATK;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'628',0) INTO :BBKPK_ALATTOKO;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'629',0) INTO :BBKPK_ALATGUDANG;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'631',0) INTO :BBKPK_LENGKAPTOKO;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'630',0) INTO :BBKPK_LENGKAPKANTOR;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'632',0) INTO :BBKPK_LENGKAPGUDANG;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'633',0) INTO :BBKPK_MATERAI;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'634',0) INTO :BBKPK_FOTOCOPY;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'635',0) INTO :BBKPK_PARKIR;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'636',0) INTO :BBKPK_ANTARDOC;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'637',0) INTO :BBKPK_POS;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'638',0) INTO :BBKPK_IZIN;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'639',0) INTO :BBKPK_STNK;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'640',0) INTO :BBKPK_NOTARIS;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'650',0) INTO :BOL_AKOMODASI;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'651',0) INTO :BOL_KONSUMSI;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'652',0) INTO :BOL_PRODUKSI;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'653',0) INTO :BOL_BONGKARAN;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'654',0) INTO :BOL_KIRIMLUAR;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'655',0) INTO :BOL_TRIPBISNIS;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'656',0) INTO :BOL_ENTERTAIMENT;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'673',0) INTO :BPP_KENDARAAN;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'674',0) INTO :BPP_GEDUNG;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'675',0) INTO :BYA_ADMINBANK;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'182',0) INTO :BYA_SEWAGEDUNG;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'680',0) INTO :PPH21;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'681',0) INTO :PPH22;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'682',0) INTO :PPH23;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'683',0) INTO :PPH2529;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'705',0) INTO :PENDAPATAN_CLAIM;
  SELECT JUMLAH FROM GET_JUMLAHSALDO(:BULAN,:TAHUN,'701',0) INTO :PENDAPATAN_GIRO;
  TOTAL_OPERASIONAL = COALESCE(BTK_GAJI,0)+COALESCE(TUNJANGAN_THR,0)+COALESCE(TUNJANGAN_SERAGAM,0)+COALESCE(INSENTIF,0)+COALESCE(BBJPK_PROMOSI,0)+COALESCE(BBKPK_LISTRIK,0)+COALESCE(BBKPK_TELPON,0)+COALESCE(BBKPK_AIR,0)+COALESCE(BBKPK_KOM,0)+COALESCE(BBKPK_BBM,0)+COALESCE(BBKPK_CETAKAN,0)+COALESCE(BBKPK_ATK,0)+COALESCE(BBKPK_ALATTOKO,0)+COALESCE(BBKPK_ALATGUDANG,0)+COALESCE(BBKPK_LENGKAPTOKO,0)+COALESCE(BBKPK_LENGKAPKANTOR,0)+COALESCE(BBKPK_LENGKAPGUDANG,0)+COALESCE(BBKPK_MATERAI,0)+COALESCE(BBKPK_FOTOCOPY,0)+COALESCE(BBKPK_PARKIR,0)+COALESCE(BBKPK_ANTARDOC,0)+COALESCE(BBKPK_POS,0)+COALESCE(BBKPK_IZIN,0)+COALESCE(BBKPK_STNK,0)+COALESCE(BBKPK_NOTARIS,0)+COALESCE(BOL_AKOMODASI,0)+COALESCE(BOL_KONSUMSI,0)+COALESCE(BOL_PRODUKSI,0)+COALESCE(BOL_BONGKARAN,0)+COALESCE(BOL_KIRIMLUAR,0)+COALESCE(BOL_TRIPBISNIS,0)+COALESCE(BOL_ENTERTAIMENT,0)+COALESCE(BPP_KENDARAAN,0)+COALESCE(BPP_GEDUNG,0)+COALESCE(BYA_ADMINBANK,0)+COALESCE(BYA_SEWAGEDUNG,0)+COALESCE(PPH21,0)+COALESCE(PPH22,0)+COALESCE(PPH23,0)+COALESCE(PPH2529,0);
  SUSPEND;
END;
