CREATE PROCEDURE SUNDA_MOTOR_KODE_CUSTOMER
RETURNS(
  KODE VARCHAR(20))
AS
DECLARE VARIABLE LAST_NUMBER INTEGER;
DECLARE VARIABLE TEMPLATE VARCHAR(20);
DECLARE VARIABLE CHAR_LAST_NUMBER VARCHAR(20);
BEGIN
  -- CONTOH KODE : K-00000000
  -- CARI ANGKA TERAKHIR
  LAST_NUMBER = 0;
  TEMPLATE = 'K-00000000';
  SELECT 
  COALESCE(MAX(CAST(SUBSTRING(KODE_CUSTOMER FROM 3 FOR STRLEN(KODE_CUSTOMER)) AS INTEGER)),1)
  FROM MST_CUSTOMER
  WHERE KODE_CUSTOMER LIKE 'K-%'
  INTO :LAST_NUMBER;
  
  IF(LAST_NUMBER = 0) THEN
  LAST_NUMBER = 1;
  ELSE
  LAST_NUMBER = LAST_NUMBER + 1;
  
  CHAR_LAST_NUMBER = CAST(LAST_NUMBER AS VARCHAR(20));
  IF(STRLEN(CHAR_LAST_NUMBER) > 8) THEN
    KODE = 'K-' || CHAR_LAST_NUMBER;
  ELSE
    KODE = SUBSTRING(TEMPLATE FROM 1 FOR STRLEN(TEMPLATE)-STRLEN(CHAR_LAST_NUMBER)) || CHAR_LAST_NUMBER;
  SUSPEND;
END;
