ALTER TRIGGER DT_PEMBELIAN_AI
ACTIVE BEFORE 
  INSERT
POSITION 20
AS
DECLARE VARIABLE NO_KARTU BIGINT;
DECLARE VARIABLE TANGGAL DATE;
DECLARE VARIABLE USER_INPUT VARCHAR(20);
DECLARE VARIABLE WAKTU_INPUT TIMESTAMP;
DECLARE VARIABLE KODE_BARANG VARCHAR(20);
DECLARE VARIABLE TMP BIGINT;
BEGIN
  -- ambil data header penjualan
  SELECT TANGGAL, USER_INPUT, WAKTU_INPUT FROM MT_PEMBELIAN
  WHERE
  NO_FAKTUR = NEW.NO_FAKTUR
  INTO :TANGGAL, :USER_INPUT, :WAKTU_INPUT;
  
  SELECT KODE_BARANG FROM MST_BARANG_JUAL
  WHERE KODE_JUAL = NEW.KODE_BARANG AND KODE_SATUAN = NEW.KODE_SATUAN
  INTO :KODE_BARANG;

  -- insert ke kartu stock
  EXECUTE PROCEDURE TOOLS_INSERTKARTUSTOCK
  (:TANGGAL,new.GUDANG,:KODE_BARANG,NEW.QTY*new.konversi,'PEMBELIAN',NEW.NO_FAKTUR,
  'TRANSAKSI PEMBELIAN',:USER_INPUT, :WAKTU_INPUT, new.qty, new.KODE_SATUAN, NEW.BATCH, NEW.TGL_EXP, NEW.SERIAL)  
  RETURNING_VALUES NEW.NO_KARTU_STOCK;
  
  --INSERT JIKA ADA BONUS PEMBELIAN
  IF(COALESCE(NEW.QTY_BONUS,0) > 0) THEN
  BEGIN
  EXECUTE PROCEDURE TOOLS_INSERTKARTUSTOCK
  (:TANGGAL,new.GUDANG,:KODE_BARANG,NEW.QTY_BONUS*new.konversi,'PEMBELIAN',NEW.NO_FAKTUR,
  'TRANSAKSI PEMBELIAN - BONUS',:USER_INPUT, :WAKTU_INPUT, new.qty_BONUS, new.KODE_SATUAN, NEW.BATCH, NEW.TGL_EXP, NEW.SERIAL)
  RETURNING_VALUES :TMP;
  END
  
END;
