CREATE GENERATOR GSI_CUSTOMER_FITUR_NO_FITUR_GEN;

CREATE TRIGGER BI_GSI_CUSTOMER_FITUR_NO_FITUR FOR GSI_CUSTOMER_FITUR
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.NO_FITUR IS NULL) THEN
      NEW.NO_FITUR = GEN_ID(GSI_CUSTOMER_FITUR_NO_FITUR_GEN, 1);
END;

SET GENERATOR GSI_CUSTOMER_FITUR_NO_FITUR_GEN TO 125;

--ALTER TABLE GSI_CUSTOMER_FITUR ADD CABANG_VPS INTEGER;
CREATE PROCEDURE UPDATE_CABANG_GSI
RETURNS(
  CABANGNYA SMALLINT)
AS
DECLARE VARIABLE NO_FITUR INTEGER;
DECLARE VARIABLE CABANG INTEGER;
BEGIN
   FOR
     SELECT NO_FITUR FROM GSI_CUSTOMER_FITUR
     WHERE COALESCE(VPS,0) = 1
     AND COALESCE(TRIAL,0) = 0
     INTO :NO_FITUR
   DO
   BEGIN
     SELECT FIRST 1 NOMINAL/100000 FROM GSI_PEMBAYARAN_FITUR
     WHERE EXTRACT(MONTH FROM TANGGAL) = 8
     AND EXTRACT(YEAR FROM TANGGAL) = 2022
     AND NO_FITUR = :NO_FITUR
     INTO :CABANG;
     
     
     UPDATE GSI_CUSTOMER_FITUR
     SET CABANG_VPS = :CABANG
     WHERE NO_FITUR = :NO_FITUR;
   END
END;
