CREATE PROCEDURE UPDATE_TAMPIL
RETURNS(
  KODE_BARANG VARCHAR(20))
AS
BEGIN
 FOR
   SELECT KODE_BARANG
   FROM TMP_SUNDA
   WHERE COALESCE(HAPUS,0) = 1
   INTO :KODE_BARANG
 DO
 BEGIN
   UPDATE MST_BARANG SET TAMPIL = 0
   WHERE KODE_BARANG = :KODE_BARANG;
 END
END;
