CREATE PROCEDURE UPDATE_HARGA
RETURNS(
  KODE_BARANG VARCHAR(20),
  HARGA_BELI DECIMAL(18, 2),
  HARGA_JUAL DECIMAL(18, 2),
  HARGA_JUAL2 DECIMAL(18, 2),
  HARGA_JUAL3 DECIMAL(18, 2),
  HARGA_JUAL4 DECIMAL(18, 2),
  HARGA_JUAL5 DECIMAL(18, 2),
  NODATA BIGINT,
  BARCODE VARCHAR(20))
AS
DECLARE VARIABLE NEW_VAR SMALLINT;
BEGIN
FOR
  SELECT A.KODE_BARANG,
  A.HARGA_BELI,A.HARGA_JUAL,A.HARGA_JUAL2,A.HARGA_JUAL3,A.HARGA_JUAL4,A.HARGA_JUAL5,
  B.KODE_JUAL,B.NODATA
  FROM TMP_SUNDA A
  INNER JOIN MST_BARANG_JUAL B ON B.KODE_BARANG = A.KODE_BARANG
  WHERE
  COALESCE(A.HARGA_BELI,0) > 0 OR
  COALESCE(A.HARGA_JUAL,0) > 0 OR
  COALESCE(A.HARGA_JUAL2,0) > 0 OR
  COALESCE(A.HARGA_JUAL3,0) > 0 OR
  COALESCE(A.HARGA_JUAL4,0) > 0 OR
  COALESCE(A.HARGA_JUAL5,0) > 0
  INTO :KODE_BARANG,:HARGA_BELI,:HARGA_JUAL,:HARGA_JUAL2,:HARGA_JUAL3,:HARGA_JUAL4,:HARGA_JUAL5,
  :BARCODE,:NODATA

DO
  BEGIN
    IF(EXISTS(SELECT KODE_BARANG FROM MST_BARANG_JUAL WHERE KODE_BARANG = :KODE_BARANG))THEN
    BEGIN
      UPDATE MST_BARANG_JUAL
      SET 
      HARGA_POKOK = COALESCE(:HARGA_BELI,0),
      HARGA_POKOK_KOTOR = COALESCE(:HARGA_BELI,0),
      HARGA_JUAL = COALESCE(:HARGA_JUAL,0),
      HARGA_JUAL2 = COALESCE(:HARGA_JUAL2,0),
      HARGA_JUAL3 = COALESCE(:HARGA_JUAL3,0),
      HARGA_JUAL4 = COALESCE(:HARGA_JUAL4,0),
      HARGA_JUAL5 = COALESCE(:HARGA_JUAL5,0)
      WHERE NODATA = :NODATA;
    END
  END
END;
