CREATE PROCEDURE UPDATE_BARCODE
RETURNS(
  KODE_JUAL VARCHAR(20),
  KODE_BARANG VARCHAR(20),
  NO_URUT BIGINT)
AS
DECLARE VARIABLE NEW_VAR SMALLINT;
BEGIN
FOR
  SELECT KODE_JUAL,KODE_BARANG,NODATA
  FROM MST_BARANG_JUAL A
  WHERE STRLEN(KODE_JUAL) = 4
  INTO :KODE_JUAL,:KODE_BARANG,:NO_URUT
DO
  BEGIN
  UPDATE MST_BARANG_JUAL
  SET KODE_JUAL = SUBSTRING(:KODE_JUAL FROM 1 FOR 1) || '0' || SUBSTRING(:KODE_JUAL FROM 2 FOR STRLEN(:KODE_JUAL))
  WHERE NODATA = :NO_URUT;
  END
END;
