CREATE PROCEDURE VW_PEMBAYARAN_FITUR(
  BULAN INTEGER,
  TAHUN INTEGER,
  JENIS VARCHAR(20))
RETURNS(
  NO_FITUR BIGINT,
  KODE_CUSTOMER VARCHAR(20),
  NAMA_CUSTOMER VARCHAR(200),
  TELP VARCHAR(20),
  ALIAS VARCHAR(100),
  BAYAR_VPS SMALLINT,
  BAYAR_VPN SMALLINT,
  BAYAR_MYFTP SMALLINT,
  BAYAR_WHATSAPP SMALLINT,
  BAYAR_MOBILE SMALLINT)
AS
DECLARE VARIABLE NEW_VAR SMALLINT;
BEGIN
  FOR
  EXECUTE STATEMENT
  'SELECT 
  A.NO_FITUR,A.KODE_CUSTOMER,A.NAMA_CUSTOMER,A.DB_ALIAS,B.TELP
  FROM GSI_CUSTOMER_FITUR A
  INNER JOIN MST_CUSTOMER B ON B.KODE_CUSTOMER = A.KODE_CUSTOMER
  WHERE COALESCE(A.'||:JENIS||',0) = 1 AND COALESCE(A.TRIAL,0) = 0'
  INTO :NO_FITUR,:KODE_CUSTOMER,:NAMA_CUSTOMER,:ALIAS,:TELP
  DO
  BEGIN
  BAYAR_VPS = 0;BAYAR_VPN = 0;BAYAR_MYFTP = 0; BAYAR_WHATSAPP = 0;BAYAR_MOBILE = 0;
  -- CEK PEMBAYARAN
  EXECUTE STATEMENT
  'SELECT FIRST 1
   VPS,VPN,MYFTP,WHATSAPP,MOBILE
   FROM GSI_PEMBAYARAN_FITUR
   WHERE NO_FITUR = '|| :NO_FITUR || '
   AND COALESCE(BATAL,0) = 0
   AND COALESCE('||:JENIS||',0) = 1
   AND EXTRACT(MONTH FROM TANGGAL) = ' || :BULAN || '
   AND EXTRACT(YEAR FROM TANGGAL) = ' || :TAHUN 
   INTO :BAYAR_VPS,:BAYAR_VPN,:BAYAR_MYFTP,:BAYAR_WHATSAPP,:BAYAR_MOBILE;
   SUSPEND;
  END
END;
